#### 2 Manipulação de Dados em Python com NumPy / Pablo Ignacio Morel A.

In [ ]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
#!pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
!pip install -q -U watermark

In [2]:
# Importando o módulo NumPy
import numpy as np

In [ ]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "Data Science Academy" --iversions

### Criando Estruturas de Dados com Outras Funções

In [3]:
# Array 10x8 de zeros
array6 = np.zeros((10,8)); array6

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

#### numpy.ones

In [4]:
# Array 2x3x2 de 1's
array7 = np.ones((2, 3, 2)); array7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

### numpy.eye

In [6]:
# Produz uma Matriz Identidade
array8 = np.eye(3); array8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### numpy.diag

In [8]:
# Matriz diagonal
array9 = np.diag((2,1,4,6)); array9

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

### numpy.random.rand

In [9]:
# A função rand(n) produz uma sequência de números uniformemente distribuídos com range de 0 a n
np.random.seed(100) # Set seed
array10 = np.random.rand(5); array10

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [10]:
# A função randn(n) produz uma sequência de números com distribuição normal (Gaussian)
array11 = np.random.randn(5); array11

array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

#### numpy.empty

In [12]:
array12 = np.empty((3,2)); array12

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### numpy.tile

In [14]:
np.array([[9, 4], [3, 7]])

array([[9, 4],
       [3, 7]])

In [15]:
np.tile(np.array([[9, 4], [3, 7]]), 4)

array([[9, 4, 9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7, 3, 7]])

In [16]:
np.tile(np.array([[9, 4], [3, 7]]), (2,2))

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])

#### Tipos de Dados NumPy

In [17]:
array13 = np.array([8, -3, 5, 9], dtype = 'float')

In [18]:
print(array13)

[ 8. -3.  5.  9.]


In [20]:
array13.dtype

dtype('float64')

In [21]:
array14 = np.array([2, 4, 6, 8])

In [22]:
print(array14)

[2 4 6 8]


In [23]:
array14.dtype

dtype('int32')

In [24]:
array15 = np.array([2.0, 4, 6, 8])

In [25]:
array15.dtype

dtype('float64')

In [26]:
array16 = np.array(['Data','Science','Academy'])

In [27]:
array16.dtype

dtype('<U7')

In [28]:
array17 = np.array([True, False, True])

In [29]:
array17.dtype

dtype('bool')

In [30]:
array18 = np.array([7, -3, 5.24])

In [31]:
array18.dtype

dtype('float64')

In [32]:
array18.astype(int)

array([ 7, -3,  5])

In [33]:
array18.dtype

dtype('float64')

### Operações com Arrays

In [35]:
# Array começando por 0, com 30 elementos e multiplicado por 5
array19 = np.arange(0, 30) * 5; array19

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145])

In [36]:
# Elevando um array a quarta potência (** potência)
array20 = np.arange(5) ** 4; array20

array([  0,   1,  16,  81, 256], dtype=int32)

In [37]:
# Somando um número a cada elemento do array
array21 = np.arange(0, 30) + 1

In [38]:
print(array21)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [39]:
array22 = np.arange(0, 30, 3) + 3
array23 = np.arange(1,11)

In [40]:
array22

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [41]:
array23

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
# Subtração
array22 - array23

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [43]:
# Soma
array22 + array23

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [44]:
# Divisão
array22 / array23

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [45]:
# Multiplicação
array22 * array23

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

In [46]:
# Podemos ainda comparar arrays
array22 > array23

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [47]:
arr1 = np.array([True,False,True,False])
arr2 = np.array([False,False,True,False])
np.logical_and(arr1, arr2)

array([False, False,  True, False])

##### Podemos criar arrays com Python, sem usar o módulo NumPy. Porém o NumPy é muito mais rápido.

In [51]:
array_numpy = np.arange(1000)
%timeit array_numpy ** 4

7.9 µs ± 431 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [52]:
array_python = range(1000)
%timeit [array_python[i] ** 4 for i in array_python]

850 µs ± 117 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


#### Fim