#### Manipulação de Dados em Python com NumPy - Cap02 / Pablo Ignacio Morel A. 

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.7


In [2]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
# !pip install -q -U watermark

In [3]:
# Importando o módulo Numpy
import numpy as np

In [ ]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "Data Science Academy" --iversions

### Transposição e Reshaping de Arrays

In [4]:
array1 = np.array([[65, 23, 19], [41, 87, 10]])

In [5]:
array1

array([[65, 23, 19],
       [41, 87, 10]])

In [6]:
array1.T

array([[65, 41],
       [23, 87],
       [19, 10]])

In [7]:
np.transpose(array1)

array([[65, 41],
       [23, 87],
       [19, 10]])

### Broadcasting

In [8]:
array2 = np.array([[33, 34, 35]])

In [9]:
array2

array([[33, 34, 35]])

In [10]:
array2.T

array([[33],
       [34],
       [35]])

In [11]:
array2.T + array2

array([[66, 67, 68],
       [67, 68, 69],
       [68, 69, 70]])

### Transformando Matrizes em Vetores

In [12]:
array3 = np.array([np.arange(1,6), np.arange(10,15)])

In [13]:
array3

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [14]:
array3.ndim

2

In [15]:
array3.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [16]:
array3.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

### Operadores Lógicos

In [17]:
np.random.seed(100)
array4 = np.random.randint(1, 10, size = (4,4))

In [18]:
array4

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5]])

In [19]:
np.any((array4 % 7) == 0)

False

In [20]:
np.all(array4 < 11)

True

In [21]:
# Retorne a linha onde o elemento de índice 1 na coluna seja maior que 2 e menor que 9
np.where(np.logical_and(array4[:,1] > 2, array4[:,1] < 9 ))

(array([2], dtype=int64),)

In [22]:
# Mesmo resultado que a linha anterior
np.intersect1d(np.where(array4[:,1] > 2), np.where(array4[:,1] < 9))

array([2], dtype=int64)

In [23]:
 array4[2]

array([6, 3, 3, 3])

### Reshaping e Ordenação de Arrays

In [25]:
array5 = np.arange(1,16)

In [26]:
array5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
array5.ndim

1

In [28]:
array5.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [29]:
array7 = np.array([[3,2],[10,-1]])

In [30]:
array7

array([[ 3,  2],
       [10, -1]])

In [31]:
# Ordenando por linhas
array7.sort(axis = 1)

In [32]:
array7

array([[ 2,  3],
       [-1, 10]])

In [33]:
array8 = np.array([[3,2],[10,-1]])

In [34]:
array8

array([[ 3,  2],
       [10, -1]])

In [35]:
array8.sort(axis = 0)

In [36]:
array8

array([[ 3, -1],
       [10,  2]])

### FIM